package vistas;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;

public class Principal extends javax.swing.JFrame {

    int x, y;

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        BtnHome = new rsbuttom.RSButtonMetro();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnfacturaselectronicas = new rsbuttom.RSButtonMetro();
        MenuProveedores = new rsbuttom.RSButtonMetro();
        cinco = new rsbuttom.RSButtonMetro();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        MenuFacturacion = new rsbuttom.RSButtonMetro();
        btngestionproductos = new rsbuttom.RSButtonMetro();
        btnentradaproductos = new rsbuttom.RSButtonMetro();
        BtnGestionUsuarios = new rsbuttom.RSButtonMetro();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblcedula = new javax.swing.JLabel();
        logout = new rojeru_san.RSButtonRiple();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel9 = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        lblrol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        pnlMenu.setBackground(new java.awt.Color(239, 238, 244));
        pnlMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(239, 238, 244)));

        BtnHome.setForeground(new java.awt.Color(128, 128, 131));
        BtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/home.png"))); // NOI18N
        BtnHome.setText("HOME");
        BtnHome.setColorHover(new java.awt.Color(204, 204, 204));
        BtnHome.setColorNormal(new java.awt.Color(204, 204, 204));
        BtnHome.setColorPressed(new java.awt.Color(204, 204, 204));
        BtnHome.setColorTextHover(new java.awt.Color(128, 128, 131));
        BtnHome.setColorTextNormal(new java.awt.Color(128, 128, 131));
        BtnHome.setColorTextPressed(new java.awt.Color(128, 128, 131));
        BtnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnHome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnHome.setIconTextGap(25);
        BtnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnHomeMousePressed(evt);
            }
        });
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(239, 238, 244));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(128, 128, 131));
        jLabel1.setText("Usuarios");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        btnfacturaselectronicas.setBackground(new java.awt.Color(239, 238, 244));
        btnfacturaselectronicas.setForeground(new java.awt.Color(128, 128, 131));
        btnfacturaselectronicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bill.png"))); // NOI18N
        btnfacturaselectronicas.setText("Gestion facturas Electronicas");
        btnfacturaselectronicas.setColorHover(new java.awt.Color(204, 204, 204));
        btnfacturaselectronicas.setColorNormal(new java.awt.Color(239, 238, 244));
        btnfacturaselectronicas.setColorPressed(new java.awt.Color(204, 204, 204));
        btnfacturaselectronicas.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnfacturaselectronicas.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnfacturaselectronicas.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnfacturaselectronicas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnfacturaselectronicas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnfacturaselectronicas.setIconTextGap(19);
        btnfacturaselectronicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnfacturaselectronicasMousePressed(evt);
            }
        });
        btnfacturaselectronicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacturaselectronicasActionPerformed(evt);
            }
        });

        MenuProveedores.setBackground(new java.awt.Color(239, 238, 244));
        MenuProveedores.setForeground(new java.awt.Color(128, 128, 131));
        MenuProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/network.png"))); // NOI18N
        MenuProveedores.setText("Gestion Proveedores");
        MenuProveedores.setColorHover(new java.awt.Color(204, 204, 204));
        MenuProveedores.setColorNormal(new java.awt.Color(239, 238, 244));
        MenuProveedores.setColorPressed(new java.awt.Color(204, 204, 204));
        MenuProveedores.setColorTextHover(new java.awt.Color(128, 128, 131));
        MenuProveedores.setColorTextNormal(new java.awt.Color(128, 128, 131));
        MenuProveedores.setColorTextPressed(new java.awt.Color(128, 128, 131));
        MenuProveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MenuProveedores.setIconTextGap(25);
        MenuProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuProveedoresMousePressed(evt);
            }
        });
        MenuProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProveedoresActionPerformed(evt);
            }
        });

        cinco.setBackground(new java.awt.Color(239, 238, 244));
        cinco.setForeground(new java.awt.Color(128, 128, 131));
        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/home.png"))); // NOI18N
        cinco.setText("...");
        cinco.setColorHover(new java.awt.Color(204, 204, 204));
        cinco.setColorNormal(new java.awt.Color(239, 238, 244));
        cinco.setColorPressed(new java.awt.Color(204, 204, 204));
        cinco.setColorTextHover(new java.awt.Color(128, 128, 131));
        cinco.setColorTextNormal(new java.awt.Color(128, 128, 131));
        cinco.setColorTextPressed(new java.awt.Color(128, 128, 131));
        cinco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cinco.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cinco.setIconTextGap(19);
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cincoMousePressed(evt);
            }
        });
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(239, 238, 244));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(128, 128, 131));
        jLabel3.setText("Productos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        MenuFacturacion.setBackground(new java.awt.Color(239, 238, 244));
        MenuFacturacion.setForeground(new java.awt.Color(128, 128, 131));
        MenuFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bill.png"))); // NOI18N
        MenuFacturacion.setText("Facturacion");
        MenuFacturacion.setColorHover(new java.awt.Color(204, 204, 204));
        MenuFacturacion.setColorNormal(new java.awt.Color(239, 238, 244));
        MenuFacturacion.setColorPressed(new java.awt.Color(204, 204, 204));
        MenuFacturacion.setColorTextHover(new java.awt.Color(128, 128, 131));
        MenuFacturacion.setColorTextNormal(new java.awt.Color(128, 128, 131));
        MenuFacturacion.setColorTextPressed(new java.awt.Color(128, 128, 131));
        MenuFacturacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuFacturacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MenuFacturacion.setIconTextGap(19);
        MenuFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuFacturacionMousePressed(evt);
            }
        });
        MenuFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFacturacionActionPerformed(evt);
            }
        });

        btngestionproductos.setBackground(new java.awt.Color(239, 238, 244));
        btngestionproductos.setForeground(new java.awt.Color(128, 128, 131));
        btngestionproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/new-product.png"))); // NOI18N
        btngestionproductos.setText("Gestion De Productos");
        btngestionproductos.setColorHover(new java.awt.Color(204, 204, 204));
        btngestionproductos.setColorNormal(new java.awt.Color(239, 238, 244));
        btngestionproductos.setColorPressed(new java.awt.Color(204, 204, 204));
        btngestionproductos.setColorTextHover(new java.awt.Color(128, 128, 131));
        btngestionproductos.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btngestionproductos.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btngestionproductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btngestionproductos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btngestionproductos.setIconTextGap(19);
        btngestionproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btngestionproductosMousePressed(evt);
            }
        });
        btngestionproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngestionproductosActionPerformed(evt);
            }
        });

        btnentradaproductos.setBackground(new java.awt.Color(239, 238, 244));
        btnentradaproductos.setForeground(new java.awt.Color(128, 128, 131));
        btnentradaproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/shipping.png"))); // NOI18N
        btnentradaproductos.setText("Entrada De Productos");
        btnentradaproductos.setColorHover(new java.awt.Color(204, 204, 204));
        btnentradaproductos.setColorNormal(new java.awt.Color(239, 238, 244));
        btnentradaproductos.setColorPressed(new java.awt.Color(204, 204, 204));
        btnentradaproductos.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnentradaproductos.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnentradaproductos.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnentradaproductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnentradaproductos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnentradaproductos.setIconTextGap(25);
        btnentradaproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnentradaproductosMousePressed(evt);
            }
        });
        btnentradaproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentradaproductosActionPerformed(evt);
            }
        });

        BtnGestionUsuarios.setBackground(new java.awt.Color(239, 238, 244));
        BtnGestionUsuarios.setForeground(new java.awt.Color(128, 128, 131));
        BtnGestionUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/value.png"))); // NOI18N
        BtnGestionUsuarios.setText("Gestion Usuarios");
        BtnGestionUsuarios.setColorHover(new java.awt.Color(204, 204, 204));
        BtnGestionUsuarios.setColorNormal(new java.awt.Color(239, 238, 244));
        BtnGestionUsuarios.setColorPressed(new java.awt.Color(204, 204, 204));
        BtnGestionUsuarios.setColorTextHover(new java.awt.Color(128, 128, 131));
        BtnGestionUsuarios.setColorTextNormal(new java.awt.Color(128, 128, 131));
        BtnGestionUsuarios.setColorTextPressed(new java.awt.Color(128, 128, 131));
        BtnGestionUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnGestionUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnGestionUsuarios.setIconTextGap(19);
        BtnGestionUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnGestionUsuariosMousePressed(evt);
            }
        });
        BtnGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestionUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MenuProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfacturaselectronicas, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnGestionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnentradaproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngestionproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MenuFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(BtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MenuProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnfacturaselectronicas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnGestionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(btnentradaproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btngestionproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MenuFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 8.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pnlMenu, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(38, 86, 186));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/menu.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(811, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(128, 128, 131));
        jLabel4.setText("DASHBOARD");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(128, 128, 131));
        jLabel5.setText("Ultimo Ingreso:");

        lblfecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(128, 128, 131));
        lblfecha.setText("Fecha");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(lblfecha)
                .addGap(105, 105, 105))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(lblfecha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(128, 128, 131));
        jLabel6.setText("CC.");
        pnlPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        lblcedula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblcedula.setForeground(new java.awt.Color(128, 128, 131));
        lblcedula.setText("Cedula");
        pnlPrincipal.add(lblcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        logout.setText("Log Out");
        pnlPrincipal.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 120, 30));

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Resources/Logo SUMINISTRAR Nuevo.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        pnlPrincipal.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 640, 320));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(128, 128, 131));
        jLabel9.setText("Login with:");
        pnlPrincipal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        lbluser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbluser.setForeground(new java.awt.Color(128, 128, 131));
        lbluser.setText("Username");
        pnlPrincipal.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        lblrol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblrol.setForeground(new java.awt.Color(128, 128, 131));
        lblrol.setText("ROL");
        pnlPrincipal.add(lblrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jScrollPane1.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(pnlCentro, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        if (this.BtnHome.isSelected()) {
            this.BtnHome.setColorNormal(new Color(204, 204, 204));
            this.BtnHome.setColorHover(new Color(204, 204, 204));
            this.BtnHome.setColorPressed(new Color(204, 204, 204));

            this.MenuProveedores.setColorNormal(new Color(239, 238, 244));
            this.MenuProveedores.setColorHover(new Color(204, 204, 204));
            this.MenuProveedores.setColorPressed(new Color(204, 204, 204));

            this.btnfacturaselectronicas.setColorNormal(new Color(239, 238, 244));
            this.btnfacturaselectronicas.setColorHover(new Color(204, 204, 204));
            this.btnfacturaselectronicas.setColorPressed(new Color(204, 204, 204));

            this.BtnGestionUsuarios.setColorNormal(new Color(239, 238, 244));
            this.BtnGestionUsuarios.setColorHover(new Color(204, 204, 204));
            this.BtnGestionUsuarios.setColorPressed(new Color(204, 204, 204));

            this.cinco.setColorNormal(new Color(239, 238, 244));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));

            this.btnentradaproductos.setColorNormal(new Color(239, 238, 244));
            this.btnentradaproductos.setColorHover(new Color(204, 204, 204));
            this.btnentradaproductos.setColorPressed(new Color(204, 204, 204));

            this.btngestionproductos.setColorNormal(new Color(239, 238, 244));
            this.btngestionproductos.setColorHover(new Color(204, 204, 204));
            this.btngestionproductos.setColorPressed(new Color(204, 204, 204));

            this.MenuFacturacion.setColorNormal(new Color(239, 238, 244));
            this.MenuFacturacion.setColorHover(new Color(204, 204, 204));
            this.MenuFacturacion.setColorPressed(new Color(204, 204, 204));
        } else {
            this.BtnHome.setColorNormal(new Color(239, 238, 244));
            this.BtnHome.setColorHover(new Color(204, 204, 204));
            this.BtnHome.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void BtnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomeMousePressed
        this.BtnHome.setSelected(true);
        this.MenuProveedores.setSelected(false);
        this.btnfacturaselectronicas.setSelected(false);
        this.BtnGestionUsuarios.setSelected(false);
        this.cinco.setSelected(false);
        this.btnentradaproductos.setSelected(false);
        this.btngestionproductos.setSelected(false);
        this.MenuFacturacion.setSelected(false);
    }//GEN-LAST:event_BtnHomeMousePressed

    private void btnfacturaselectronicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacturaselectronicasActionPerformed
        if (this.btnfacturaselectronicas.isSelected()) {
            this.btnfacturaselectronicas.setColorNormal(new Color(204, 204, 204));
            this.btnfacturaselectronicas.setColorHover(new Color(204, 204, 204));
            this.btnfacturaselectronicas.setColorPressed(new Color(204, 204, 204));

            this.BtnHome.setColorNormal(new Color(239, 238, 244));
            this.BtnHome.setColorHover(new Color(204, 204, 204));
            this.BtnHome.setColorPressed(new Color(204, 204, 204));

            this.MenuProveedores.setColorNormal(new Color(239, 238, 244));
            this.MenuProveedores.setColorHover(new Color(204, 204, 204));
            this.MenuProveedores.setColorPressed(new Color(204, 204, 204));

            this.BtnGestionUsuarios.setColorNormal(new Color(239, 238, 244));
            this.BtnGestionUsuarios.setColorHover(new Color(204, 204, 204));
            this.BtnGestionUsuarios.setColorPressed(new Color(204, 204, 204));

            this.cinco.setColorNormal(new Color(239, 238, 244));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));

            this.btnentradaproductos.setColorNormal(new Color(239, 238, 244));
            this.btnentradaproductos.setColorHover(new Color(204, 204, 204));
            this.btnentradaproductos.setColorPressed(new Color(204, 204, 204));

            this.btngestionproductos.setColorNormal(new Color(239, 238, 244));
            this.btngestionproductos.setColorHover(new Color(204, 204, 204));
            this.btngestionproductos.setColorPressed(new Color(204, 204, 204));

            this.MenuFacturacion.setColorNormal(new Color(239, 238, 244));
            this.MenuFacturacion.setColorHover(new Color(204, 204, 204));
            this.MenuFacturacion.setColorPressed(new Color(204, 204, 204));
        } else {
            this.btnfacturaselectronicas.setColorNormal(new Color(239, 238, 244));
            this.btnfacturaselectronicas.setColorHover(new Color(204, 204, 204));
            this.btnfacturaselectronicas.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btnfacturaselectronicasActionPerformed

    private void btnfacturaselectronicasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfacturaselectronicasMousePressed
        this.BtnHome.setSelected(false);
        this.MenuProveedores.setSelected(false);
        this.btnfacturaselectronicas.setSelected(true);
        this.BtnGestionUsuarios.setSelected(false);
        this.cinco.setSelected(false);
        this.btnentradaproductos.setSelected(false);
        this.btngestionproductos.setSelected(false);
        this.MenuFacturacion.setSelected(false);
    }//GEN-LAST:event_btnfacturaselectronicasMousePressed

    private void MenuProveedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuProveedoresMousePressed
        this.BtnHome.setSelected(false);
        this.MenuProveedores.setSelected(true);
        this.btnfacturaselectronicas.setSelected(false);
        this.BtnGestionUsuarios.setSelected(false);
        this.cinco.setSelected(false);
        this.btnentradaproductos.setSelected(false);
        this.btngestionproductos.setSelected(false);
        this.MenuFacturacion.setSelected(false);
    }//GEN-LAST:event_MenuProveedoresMousePressed

    private void MenuProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProveedoresActionPerformed
        if (this.MenuProveedores.isSelected()) {
            this.MenuProveedores.setColorNormal(new Color(204, 204, 204));
            this.MenuProveedores.setColorHover(new Color(204, 204, 204));
            this.MenuProveedores.setColorPressed(new Color(204, 204, 204));

            this.BtnHome.setColorNormal(new Color(239, 238, 244));
            this.BtnHome.setColorHover(new Color(204, 204, 204));
            this.BtnHome.setColorPressed(new Color(204, 204, 204));

            this.btnfacturaselectronicas.setColorNormal(new Color(239, 238, 244));
            this.btnfacturaselectronicas.setColorHover(new Color(204, 204, 204));
            this.btnfacturaselectronicas.setColorPressed(new Color(204, 204, 204));

            this.BtnGestionUsuarios.setColorNormal(new Color(239, 238, 244));
            this.BtnGestionUsuarios.setColorHover(new Color(204, 204, 204));
            this.BtnGestionUsuarios.setColorPressed(new Color(204, 204, 204));

            this.cinco.setColorNormal(new Color(239, 238, 244));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));

            this.btnentradaproductos.setColorNormal(new Color(239, 238, 244));
            this.btnentradaproductos.setColorHover(new Color(204, 204, 204));
            this.btnentradaproductos.setColorPressed(new Color(204, 204, 204));

            this.btngestionproductos.setColorNormal(new Color(239, 238, 244));
            this.btngestionproductos.setColorHover(new Color(204, 204, 204));
            this.btngestionproductos.setColorPressed(new Color(204, 204, 204));

            this.MenuFacturacion.setColorNormal(new Color(239, 238, 244));
            this.MenuFacturacion.setColorHover(new Color(204, 204, 204));
            this.MenuFacturacion.setColorPressed(new Color(204, 204, 204));
        } else {
            this.MenuProveedores.setColorNormal(new Color(239, 238, 244));
            this.MenuProveedores.setColorHover(new Color(204, 204, 204));
            this.MenuProveedores.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_MenuProveedoresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int posicion = pnlMenu.getX();
        if (posicion > -1) {
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, pnlMenu);
        } else {
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, pnlMenu);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MenuFacturacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuFacturacionMousePressed
        this.BtnHome.setSelected(false);
        this.MenuProveedores.setSelected(false);
        this.btnfacturaselectronicas.setSelected(false);
        this.BtnGestionUsuarios.setSelected(false);
        this.cinco.setSelected(false);
        this.btnentradaproductos.setSelected(false);
        this.btngestionproductos.setSelected(false);
        this.MenuFacturacion.setSelected(true);
    }//GEN-LAST:event_MenuFacturacionMousePressed

    private void MenuFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFacturacionActionPerformed
        if (this.MenuFacturacion.isSelected()) {
            this.BtnHome.setColorNormal(new Color(239, 238, 244));
            this.BtnHome.setColorHover(new Color(204, 204, 204));
            this.BtnHome.setColorPressed(new Color(204, 204, 204));

            this.MenuProveedores.setColorNormal(new Color(239, 238, 244));
            this.MenuProveedores.setColorHover(new Color(204, 204, 204));
            this.MenuProveedores.setColorPressed(new Color(204, 204, 204));

            this.btnfacturaselectronicas.setColorNormal(new Color(239, 238, 244));
            this.btnfacturaselectronicas.setColorHover(new Color(204, 204, 204));
            this.btnfacturaselectronicas.setColorPressed(new Color(204, 204, 204));

            this.BtnGestionUsuarios.setColorNormal(new Color(239, 238, 244));
            this.BtnGestionUsuarios.setColorHover(new Color(204, 204, 204));
            this.BtnGestionUsuarios.setColorPressed(new Color(204, 204, 204));

            this.cinco.setColorNormal(new Color(239, 238, 244));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));

            this.btnentradaproductos.setColorNormal(new Color(239, 238, 244));
            this.btnentradaproductos.setColorHover(new Color(204, 204, 204));
            this.btnentradaproductos.setColorPressed(new Color(204, 204, 204));

            this.btngestionproductos.setColorNormal(new Color(239, 238, 244));
            this.btngestionproductos.setColorHover(new Color(204, 204, 204));
            this.btngestionproductos.setColorPressed(new Color(204, 204, 204));

            this.MenuFacturacion.setColorNormal(new Color(204, 204, 204));
            this.MenuFacturacion.setColorHover(new Color(204, 204, 204));
            this.MenuFacturacion.setColorPressed(new Color(204, 204, 204));
        } else {
            this.MenuFacturacion.setColorNormal(new Color(239, 238, 244));
            this.MenuFacturacion.setColorHover(new Color(204, 204, 204));
            this.MenuFacturacion.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_MenuFacturacionActionPerformed

    private void btngestionproductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngestionproductosMousePressed
        this.BtnHome.setSelected(false);
        this.MenuProveedores.setSelected(false);
        this.btnfacturaselectronicas.setSelected(false);
        this.BtnGestionUsuarios.setSelected(false);
        this.cinco.setSelected(false);
        this.btnentradaproductos.setSelected(false);
        this.btngestionproductos.setSelected(true);
        this.MenuFacturacion.setSelected(false);
    }//GEN-LAST:event_btngestionproductosMousePressed

    private void btngestionproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngestionproductosActionPerformed
        if (this.btngestionproductos.isSelected()) {
            this.BtnHome.setColorNormal(new Color(239, 238, 244));
            this.BtnHome.setColorHover(new Color(204, 204, 204));
            this.BtnHome.setColorPressed(new Color(204, 204, 204));

            this.MenuProveedores.setColorNormal(new Color(239, 238, 244));
            this.MenuProveedores.setColorHover(new Color(204, 204, 204));
            this.MenuProveedores.setColorPressed(new Color(204, 204, 204));

            this.btnfacturaselectronicas.setColorNormal(new Color(239, 238, 244));
            this.btnfacturaselectronicas.setColorHover(new Color(204, 204, 204));
            this.btnfacturaselectronicas.setColorPressed(new Color(204, 204, 204));

            this.BtnGestionUsuarios.setColorNormal(new Color(239, 238, 244));
            this.BtnGestionUsuarios.setColorHover(new Color(204, 204, 204));
            this.BtnGestionUsuarios.setColorPressed(new Color(204, 204, 204));

            this.cinco.setColorNormal(new Color(239, 238, 244));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));

            this.btnentradaproductos.setColorNormal(new Color(239, 238, 244));
            this.btnentradaproductos.setColorHover(new Color(204, 204, 204));
            this.btnentradaproductos.setColorPressed(new Color(204, 204, 204));

            this.btngestionproductos.setColorNormal(new Color(204, 204, 204));
            this.btngestionproductos.setColorHover(new Color(204, 204, 204));
            this.btngestionproductos.setColorPressed(new Color(204, 204, 204));

            this.MenuFacturacion.setColorNormal(new Color(239, 238, 244));
            this.MenuFacturacion.setColorHover(new Color(204, 204, 204));
            this.MenuFacturacion.setColorPressed(new Color(204, 204, 204));
        } else {
            this.btngestionproductos.setColorNormal(new Color(239, 238, 244));
            this.btngestionproductos.setColorHover(new Color(204, 204, 204));
            this.btngestionproductos.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btngestionproductosActionPerformed

    private void btnentradaproductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnentradaproductosMousePressed
        this.BtnHome.setSelected(false);
        this.MenuProveedores.setSelected(false);
        this.btnfacturaselectronicas.setSelected(false);
        this.BtnGestionUsuarios.setSelected(false);
        this.cinco.setSelected(false);
        this.btnentradaproductos.setSelected(true);
        this.btngestionproductos.setSelected(false);
        this.MenuFacturacion.setSelected(false);
    }//GEN-LAST:event_btnentradaproductosMousePressed

    private void btnentradaproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentradaproductosActionPerformed
        if (this.btnentradaproductos.isSelected()) {
            this.BtnHome.setColorNormal(new Color(239, 238, 244));
            this.BtnHome.setColorHover(new Color(204, 204, 204));
            this.BtnHome.setColorPressed(new Color(204, 204, 204));

            this.MenuProveedores.setColorNormal(new Color(239, 238, 244));
            this.MenuProveedores.setColorHover(new Color(204, 204, 204));
            this.MenuProveedores.setColorPressed(new Color(204, 204, 204));

            this.btnfacturaselectronicas.setColorNormal(new Color(239, 238, 244));
            this.btnfacturaselectronicas.setColorHover(new Color(204, 204, 204));
            this.btnfacturaselectronicas.setColorPressed(new Color(204, 204, 204));

            this.BtnGestionUsuarios.setColorNormal(new Color(239, 238, 244));
            this.BtnGestionUsuarios.setColorHover(new Color(204, 204, 204));
            this.BtnGestionUsuarios.setColorPressed(new Color(204, 204, 204));

            this.cinco.setColorNormal(new Color(239, 238, 244));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));

            this.btnentradaproductos.setColorNormal(new Color(204, 204, 204));
            this.btnentradaproductos.setColorHover(new Color(204, 204, 204));
            this.btnentradaproductos.setColorPressed(new Color(204, 204, 204));

            this.btngestionproductos.setColorNormal(new Color(239, 238, 244));
            this.btngestionproductos.setColorHover(new Color(204, 204, 204));
            this.btngestionproductos.setColorPressed(new Color(204, 204, 204));

            this.MenuFacturacion.setColorNormal(new Color(239, 238, 244));
            this.MenuFacturacion.setColorHover(new Color(204, 204, 204));
            this.MenuFacturacion.setColorPressed(new Color(204, 204, 204));
        } else {
            this.btnentradaproductos.setColorNormal(new Color(239, 238, 244));
            this.btnentradaproductos.setColorHover(new Color(204, 204, 204));
            this.btnentradaproductos.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btnentradaproductosActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        if (this.cinco.isSelected()) {
            this.BtnHome.setColorNormal(new Color(239, 238, 244));
            this.BtnHome.setColorHover(new Color(204, 204, 204));
            this.BtnHome.setColorPressed(new Color(204, 204, 204));

            this.MenuProveedores.setColorNormal(new Color(239, 238, 244));
            this.MenuProveedores.setColorHover(new Color(204, 204, 204));
            this.MenuProveedores.setColorPressed(new Color(204, 204, 204));

            this.btnfacturaselectronicas.setColorNormal(new Color(239, 238, 244));
            this.btnfacturaselectronicas.setColorHover(new Color(204, 204, 204));
            this.btnfacturaselectronicas.setColorPressed(new Color(204, 204, 204));

            this.BtnGestionUsuarios.setColorNormal(new Color(239, 238, 244));
            this.BtnGestionUsuarios.setColorHover(new Color(204, 204, 204));
            this.BtnGestionUsuarios.setColorPressed(new Color(204, 204, 204));

            this.cinco.setColorNormal(new Color(204, 204, 204));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));

            this.btnentradaproductos.setColorNormal(new Color(239, 238, 244));
            this.btnentradaproductos.setColorHover(new Color(204, 204, 204));
            this.btnentradaproductos.setColorPressed(new Color(204, 204, 204));

            this.btngestionproductos.setColorNormal(new Color(239, 238, 244));
            this.btngestionproductos.setColorHover(new Color(204, 204, 204));
            this.btngestionproductos.setColorPressed(new Color(204, 204, 204));

            this.MenuFacturacion.setColorNormal(new Color(239, 238, 244));
            this.MenuFacturacion.setColorHover(new Color(204, 204, 204));
            this.MenuFacturacion.setColorPressed(new Color(204, 204, 204));
        } else {
            this.cinco.setColorNormal(new Color(239, 238, 244));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_cincoActionPerformed

    private void cincoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMousePressed
        this.BtnHome.setSelected(false);
        this.MenuProveedores.setSelected(false);
        this.btnfacturaselectronicas.setSelected(false);
        this.BtnGestionUsuarios.setSelected(false);
        this.cinco.setSelected(true);
        this.btnentradaproductos.setSelected(false);
        this.btngestionproductos.setSelected(false);
        this.MenuFacturacion.setSelected(false);
    }//GEN-LAST:event_cincoMousePressed

    private void BtnGestionUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGestionUsuariosMousePressed
        this.BtnHome.setSelected(false);
        this.MenuProveedores.setSelected(false);
        this.btnfacturaselectronicas.setSelected(false);
        this.BtnGestionUsuarios.setSelected(true);
        this.cinco.setSelected(false);
        this.btnentradaproductos.setSelected(false);
        this.btngestionproductos.setSelected(false);
        this.MenuFacturacion.setSelected(false);
    }//GEN-LAST:event_BtnGestionUsuariosMousePressed

    private void BtnGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestionUsuariosActionPerformed
        if (this.BtnGestionUsuarios.isSelected()) {
            this.BtnHome.setColorNormal(new Color(239, 238, 244));
            this.BtnHome.setColorHover(new Color(204, 204, 204));
            this.BtnHome.setColorPressed(new Color(204, 204, 204));

            this.MenuProveedores.setColorNormal(new Color(239, 238, 244));
            this.MenuProveedores.setColorHover(new Color(204, 204, 204));
            this.MenuProveedores.setColorPressed(new Color(204, 204, 204));

            this.btnfacturaselectronicas.setColorNormal(new Color(239, 238, 244));
            this.btnfacturaselectronicas.setColorHover(new Color(204, 204, 204));
            this.btnfacturaselectronicas.setColorPressed(new Color(204, 204, 204));

            this.BtnGestionUsuarios.setColorNormal(new Color(204, 204, 204));
            this.BtnGestionUsuarios.setColorHover(new Color(204, 204, 204));
            this.BtnGestionUsuarios.setColorPressed(new Color(204, 204, 204));

            this.cinco.setColorNormal(new Color(239, 238, 244));
            this.cinco.setColorHover(new Color(204, 204, 204));
            this.cinco.setColorPressed(new Color(204, 204, 204));

            this.btnentradaproductos.setColorNormal(new Color(239, 238, 244));
            this.btnentradaproductos.setColorHover(new Color(204, 204, 204));
            this.btnentradaproductos.setColorPressed(new Color(204, 204, 204));

            this.btngestionproductos.setColorNormal(new Color(239, 238, 244));
            this.btngestionproductos.setColorHover(new Color(204, 204, 204));
            this.btngestionproductos.setColorPressed(new Color(204, 204, 204));

            this.MenuFacturacion.setColorNormal(new Color(239, 238, 244));
            this.MenuFacturacion.setColorHover(new Color(204, 204, 204));
            this.MenuFacturacion.setColorPressed(new Color(204, 204, 204));
        } else {
            this.BtnGestionUsuarios.setColorNormal(new Color(239, 238, 244));
            this.BtnGestionUsuarios.setColorHover(new Color(204, 204, 204));
            this.BtnGestionUsuarios.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_BtnGestionUsuariosActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rsbuttom.RSButtonMetro BtnGestionUsuarios;
    public rsbuttom.RSButtonMetro BtnHome;
    public rsbuttom.RSButtonMetro MenuFacturacion;
    public rsbuttom.RSButtonMetro MenuProveedores;
    public rsbuttom.RSButtonMetro btnentradaproductos;
    public rsbuttom.RSButtonMetro btnfacturaselectronicas;
    public rsbuttom.RSButtonMetro btngestionproductos;
    public rsbuttom.RSButtonMetro cinco;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblcedula;
    public javax.swing.JLabel lblfecha;
    public javax.swing.JLabel lblrol;
    public javax.swing.JLabel lbluser;
    public rojeru_san.RSButtonRiple logout;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private rojerusan.RSPanelImage rSPanelImage1;
    // End of variables declaration//GEN-END:variables
}
